import asyncio
import logging
from koot.network.ipc.server import LocalIPCGateway
from koot.network.gateway.mtls_server import ZeroTrustGateway
from koot.core.bus.registry import AdaptiveRegistry

# Set up logging so you can see what the core is doing
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

async def boot_daemon():
    logging.info("Initializing Koot Adaptive Core...")
    
    # 1. Initialize the Registry Bus (The Brain)
    registry = AdaptiveRegistry()
    
    # 2. Local Access (IPC)
    ipc_server = LocalIPCGateway(socket_path="/tmp/koot.sock", registry=registry)
    
    # 3. Remote Access (Zero-Trust mTLS)
    # Ensure these paths match the ones generated by generate_mtls_certs.py
    mtls_gateway = ZeroTrustGateway(
        host="0.0.0.0", 
        port=8443,
        ca_cert_path="certs/ca.crt",
        server_cert_path="certs/server.crt",
        server_key_path="certs/server.key",
        shadow_ledger=registry.get_plugin("shadow_ledger") # Pass the ledger if available
    )

    # 4. Start both listeners
    logging.info("Starting IPC Server and Zero-Trust Gateway on port 8443...")
    await asyncio.gather(
        ipc_server.start(),
        mtls_gateway.start()
    )

if __name__ == "__main__":
    try:
        asyncio.run(boot_daemon())
    except KeyboardInterrupt:
        logging.info("Koot Core Daemon shutting down securely.")