import os
import pytest

def test_requirements_are_hash_pinned():
    """
    Ensures that the requirements.txt file uses strict cryptographic hash pinning 
    (SHA-256) to prevent supply chain poisoning of open-source libraries.
    """
    req_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../requirements.txt"))
    assert os.path.exists(req_path), "requirements.txt does not exist."
    
    with open(req_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Verify the file was built by pip-tools
    assert "pip-compile" in content or "pip-tools" in content, (
        "requirements.txt was not generated by pip-tools. "
        "Run `python scripts/update_requirements.py` to compile."
    )
    
    # Verify cryptographic hashes are present
    assert "--hash=sha256:" in content, (
        "No SHA-256 hashes found in requirements.txt. "
        "Supply chain hardening failed. Requirements must be pinned."
    )