import os
import ast
import sys
import subprocess
from importlib.metadata import version, PackageNotFoundError

# Define project directories to scan and local modules to ignore
def discover_local_modules(root_path):
    local_mods = set()
    for root, dirs, files in os.walk(root_path):
        if any(ignore in root for ignore in ["venv", ".git", "__pycache__"]):
            continue
        local_mods.update(dirs)
        local_mods.update(f[:-3] for f in files if f.endswith(".py"))
    return local_mods

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LOCAL_MODULES = discover_local_modules(PROJECT_ROOT)

# Get the list of Python Standard Library modules
if sys.version_info >= (3, 10):
    STDLIB_MODULES = set(sys.stdlib_module_names)
else:
    import distutils.sysconfig as sysconfig
    std_lib_dir = sysconfig.get_python_lib(standard_lib=True)
    STDLIB_MODULES = {name.split('.')[0] for name in os.listdir(std_lib_dir)}
    STDLIB_MODULES.update(sys.builtin_module_names)

# Map dynamic import names to exact PyPI package names
IMPORT_TO_PYPI_MAP = {
    "yaml": "PyYAML",
    "cv2": "opencv-python",
    "argon2": "argon2-cffi",
    "oqs": "liboqs-python",
    "tpm2_pytss": "tpm2-pytss",
    "git": "GitPython"
}

def extract_imports_from_file(filepath):
    """Parses a Python file and yields base import names."""
    with open(filepath, "r", encoding="utf-8") as file:
        try:
            tree = ast.parse(file.read(), filename=filepath)
        except SyntaxError:
            return set()

    imports = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(alias.name.split('.')[0])
        elif isinstance(node, ast.ImportFrom):
            # FIX: Explicitly ignore relative imports (level > 0).
            # This natively prevents local modules like 'base' or 'environment' from being detected.
            if node.module and node.level == 0:
                imports.add(node.module.split('.')[0])
    return imports

def scan_project_for_dependencies():
    """Walks the project directory to find all third-party dependencies."""
    third_party_imports = set()
    for root, _, files in os.walk(PROJECT_ROOT):
        if "venv" in root or ".git" in root or "__pycache__" in root:
            continue
        for file in files:
            if file.endswith(".py"):
                filepath = os.path.join(root, file)
                for imp in extract_imports_from_file(filepath):
                    if imp not in STDLIB_MODULES and imp not in LOCAL_MODULES and not imp.startswith("_"):
                        third_party_imports.add(imp)
    return third_party_imports

def generate_requirements_in(dependencies):
    """Writes the exact local dependency versions to a requirements.in file."""
    req_in_path = os.path.join(PROJECT_ROOT, "requirements.in")
    pypi_packages = [IMPORT_TO_PYPI_MAP.get(dep, dep) for dep in dependencies]
    pypi_packages.sort()

    print(f"[*] Generating requirements.in based on local environment...")
    with open(req_in_path, "w", encoding="utf-8") as f:
        f.write("# Core Dependencies - Auto-generated by scripts/update_requirements.py\n")
        for package in pypi_packages:
            try:
                # FIX: Force strict local version pinning so pip-compile doesn't blindly upgrade packages
                pkg_version = version(package)
                f.write(f"{package}=={pkg_version}\n")
                print(f"  [+] Pinned in source: {package}=={pkg_version}")
            except PackageNotFoundError:
                # Fallback if package isn't currently installed in the dev environment
                f.write(f"{package}\n")
                print(f"  [!] Not installed locally (unpinned): {package}")
                
    print(f"[*] Saved source requirements to: {req_in_path}\n")
    return req_in_path

def compile_hashed_requirements(req_in_path):
    """Uses pip-tools to generate a hash-pinned requirements.txt."""
    req_out_path = os.path.join(PROJECT_ROOT, "requirements.txt")
    print("[*] Compiling cryptographically hashed requirements.txt via pip-tools...")
    
    try:
        # Run pip-compile to lock dependencies with hashes
        subprocess.run([
            sys.executable, "-m", "piptools", "compile",
            "--generate-hashes",
            "-o", req_out_path,
            req_in_path
        ], check=True)
        print(f"\n[SUCCESS] Cryptographically secured requirements.txt created at: {req_out_path}")
    except subprocess.CalledProcessError:
        print("\n[ERROR] Failed to compile requirements.")
        print("ACTION REQUIRED: You must install pip-tools first: `pip install pip-tools`")
        sys.exit(1)

if __name__ == "__main__":
    print("[*] Scanning koot project for imports...")
    detected_deps = scan_project_for_dependencies()
    req_in = generate_requirements_in(detected_deps)
    compile_hashed_requirements(req_in)