import os
import ast
import sys
from importlib.metadata import version, PackageNotFoundError

# Define project directories to scan and local modules to ignore
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LOCAL_MODULES = {"koot", "tests", "scripts"}

# Get the list of Python Standard Library modules to ignore them
if sys.version_info >= (3, 10):
    STDLIB_MODULES = set(sys.stdlib_module_names)
else:
    # Fallback for older Python versions
    import distutils.sysconfig as sysconfig
    std_lib_dir = sysconfig.get_python_lib(standard_lib=True)
    STDLIB_MODULES = {name.split('.')[0] for name in os.listdir(std_lib_dir)}
    STDLIB_MODULES.update(sys.builtin_module_names)

# Some packages have different import names than their PyPI install names.
# Add common ones here as you expand the project.
IMPORT_TO_PYPI_MAP = {
    "yaml": "PyYAML",
    "cv2": "opencv-python",
    # "liboqs": "liboqs-python" (if you use a specific wrapper later)
}

def extract_imports_from_file(filepath):
    """Parses a Python file and yields base import names."""
    with open(filepath, "r", encoding="utf-8") as file:
        try:
            tree = ast.parse(file.read(), filename=filepath)
        except SyntaxError:
            return set()

    imports = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(alias.name.split('.')[0])
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.add(node.module.split('.')[0])
    return imports

def scan_project_for_dependencies():
    """Walks the project directory to find all third-party dependencies."""
    third_party_imports = set()

    for root, _, files in os.walk(PROJECT_ROOT):
        # Skip virtual environments and hidden directories
        if "venv" in root or ".git" in root or "__pycache__" in root:
            continue

        for file in files:
            if file.endswith(".py"):
                filepath = os.path.join(root, file)
                file_imports = extract_imports_from_file(filepath)
                
                for imp in file_imports:
                    if imp not in STDLIB_MODULES and imp not in LOCAL_MODULES and not imp.startswith("_"):
                        third_party_imports.add(imp)

    return third_party_imports

def update_requirements_file(dependencies):
    """Fetches versions and writes them to requirements.txt."""
    req_file_path = os.path.join(PROJECT_ROOT, "requirements.txt")
    
    # Map import names to PyPI names
    pypi_packages = [IMPORT_TO_PYPI_MAP.get(dep, dep) for dep in dependencies]
    pypi_packages.sort()

    print(f"[*] Found {len(pypi_packages)} third-party dependencies.")
    
    requirements_lines = [
        "# Core Dependencies - Auto-generated by scripts/update_requirements.py\n"
    ]

    for package in pypi_packages:
        try:
            # Try to get the exact version currently installed in your environment
            pkg_version = version(package)
            line = f"{package}=={pkg_version}\n"
            print(f"  [+] Pinned: {line.strip()}")
        except PackageNotFoundError:
            # If not installed, just list the package name
            line = f"{package}\n"
            print(f"  [!] Not installed locally (unpinned): {line.strip()}")
        
        requirements_lines.append(line)

    with open(req_file_path, "w", encoding="utf-8") as f:
        f.writelines(requirements_lines)
    
    print(f"\n[SUCCESS] requirements.txt has been updated at: {req_file_path}")

if __name__ == "__main__":
    print("[*] Scanning koot project for imports...")
    detected_dependencies = scan_project_for_dependencies()
    update_requirements_file(detected_dependencies)